server:
  port: 8088

lhtrpc:
  zk:
    zkServer: 192.168.3.100:2181
    zkRoot: lhtrpc
  app:
    id: lht-app
    namespace: public
    env: dev
  consumer:
    retry: 3
    grayRatio: 20 # 0~100
    okhttp:
      connectTimeout: 1000
      readTimeout: 1000
      writeTimeout: 1000

lhtregistry:
  servers: http://localhost:8084

logging:
  level:
    root: error
    com.lht.lhtrpc: debug
    com.ctrip: error


app:
  id: leoApp
apollo:
  cacheDir: F:/opt/data/                       #配置本地配置缓存目录
  cluster: default                           #指定使用哪个集群的配置
  meta: http://localhost:8080           #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: app                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前