###超时调用
GET http://localhost:8088/time?timeout=1000

###修改超时端口
GET http://localhost:8081/port?ports=8081,8094

###修改灰度率
GET http://localhost:8088/gray?grayRatio=0

###调用
GET http://localhost:8088/api?id=100

###查看元数据配置
GET http://localhost:8081/metas

###
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.lht.lhtrpc.demo.api.UserService",
  "methodSign": "find@1_int",
  "args": [200]
}

###
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.lht.lhtrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}

### 注册服务
POST http://localhost:8084/register?server=lht-app_public_dev_com.lht.lhtrpc.demo.api.OrderService
Content-Type: application/json

{"context":"lhtrpc","host":"192.168.3.55","parameters":{"unit":"C001","gray":"false","dc":"sh","tc":"10"},"port":8081,"scheme":"http","status":false}