server:
  port: 8081

lhtrpc:
  zk:
    zkServer: 192.168.3.100:2181
    zkRoot: lhtrpc
  provider:
    packages: com.lht.lhtrpc.demo.provider
    metas:
      dc: cd
      gray: false
      unit: C001
  app:
    id: lht-app
    namespace: public
    env: dev

logging:
  level:
    root: error
    com.lht.lhtrpc: debug
