server:
  port: 8081

lhtrpc:
  zkServer: 192.168.3.100:2181
  zkRoot: lhtrpc
  package: com.lht.lhtrpc.demo.provider

app:
  id: lht-app
  namespace: public
  env: dev


logging:
  level:
    root: error
    com.lht.lhtrpc: info
